name: Testbench for all RISCV modules

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run_simulations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - alu
          - decoder
          - fetch
          - imm
          - ram
          - regs
          - rom
          - store
          - load
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GHDL and dependencies
        run: |
          sudo apt update
          sudo apt install -y ghdl gtkwave make

      - name: Run Makefile for ${{ matrix.module }} testbench simulation
        working-directory: simu
        run: make ${{ matrix.module }}_sim
